# Generated by Django 5.0.3 on 2026-04-02 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0002_jemputan_user'),
        ('problems', '0002_problemstatement_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatement',
            name='jemputan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pernyataan', to='bengkel.jemputan'),
        ),
    ]
