# Generated by Django 5.0.3 on 2026-04-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bengkel',
            name='status',
        ),
    ]
