# Generated by Django 5.0.3 on 2026-04-02 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0004_remove_status_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenganjurRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Semakan'), ('approved', 'Diluluskan'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('sebab', models.TextField(blank=True, help_text='Sebab permohonan (ditulis oleh pemohon)')),
                ('catatan_admin', models.TextField(blank=True, help_text='Catatan semakan admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penganjur_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permohonan Penganjur',
                'verbose_name_plural': 'Permohonan Penganjur',
                'ordering': ['-created_at'],
            },
        ),
    ]
