# Generated by Django 5.0.3 on 2026-04-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0005_add_penganjur_request'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jemputan',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='jemputan',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='jemputan',
            name='nama',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
