# Generated by Django 5.0.3 on 2026-04-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0008_contribution_laporan'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionfile',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
