# Generated by Django 5.0.3 on 2026-04-07 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0009_contributionfile_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativeBengkel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa', models.CharField(help_text='Contoh: 08:00 - 09:00', max_length=50)),
                ('aktiviti', models.CharField(max_length=300)),
                ('penerangan', models.TextField(blank=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bengkel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentative', to='bengkel.bengkel')),
            ],
            options={
                'verbose_name': 'Tentative',
                'verbose_name_plural': 'Tentative Bengkel',
                'ordering': ['urutan', 'created_at'],
            },
        ),
    ]
