# Generated by Django 5.0.3 on 2026-04-07 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0010_tentative_bengkel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis5C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syarikat', models.TextField(verbose_name='Syarikat/Organisasi (Company)')),
                ('pelanggan', models.TextField(verbose_name='Pelanggan (Customers)')),
                ('pesaing', models.TextField(verbose_name='Pesaing (Competitors)')),
                ('rakan_kongsi', models.TextField(verbose_name='Rakan Kongsi (Collaborators)')),
                ('persekitaran', models.TextField(verbose_name='Persekitaran (Climate)')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bengkel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fivec_set', to='bengkel.bengkel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fivec_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analisis 5C',
                'verbose_name_plural': 'Analisis 5C',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalisisPESTEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politik', models.TextField(verbose_name='Faktor Politik (Political)')),
                ('ekonomi', models.TextField(verbose_name='Faktor Ekonomi (Economic)')),
                ('sosial', models.TextField(verbose_name='Faktor Sosial (Social)')),
                ('teknologi', models.TextField(verbose_name='Faktor Teknologi (Technological)')),
                ('alam_sekitar', models.TextField(verbose_name='Faktor Alam Sekitar (Environmental)')),
                ('undang_undang', models.TextField(verbose_name='Faktor Undang-Undang (Legal)')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bengkel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pestel_set', to='bengkel.bengkel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pestel_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analisis PESTEL',
                'verbose_name_plural': 'Analisis PESTEL',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalisisSOAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kekuatan', models.TextField(verbose_name='Kekuatan (Strengths)')),
                ('peluang', models.TextField(verbose_name='Peluang (Opportunities)')),
                ('aspirasi', models.TextField(verbose_name='Aspirasi (Aspirations)')),
                ('keputusan', models.TextField(verbose_name='Keputusan/Hasil (Results)')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bengkel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soar_set', to='bengkel.bengkel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soar_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analisis SOAR',
                'verbose_name_plural': 'Analisis SOAR',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalisisSWOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kekuatan', models.TextField(verbose_name='Kekuatan (Strengths)')),
                ('kelemahan', models.TextField(verbose_name='Kelemahan (Weaknesses)')),
                ('peluang', models.TextField(verbose_name='Peluang (Opportunities)')),
                ('ancaman', models.TextField(verbose_name='Ancaman (Threats)')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bengkel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swot_set', to='bengkel.bengkel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swot_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analisis SWOT',
                'verbose_name_plural': 'Analisis SWOT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalisisVMOST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi', models.TextField(verbose_name='Visi (Vision)')),
                ('misi', models.TextField(verbose_name='Misi (Mission)')),
                ('objektif', models.TextField(verbose_name='Objektif (Objectives)')),
                ('strategi', models.TextField(verbose_name='Strategi (Strategy)')),
                ('taktik', models.TextField(verbose_name='Taktik (Tactics)')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bengkel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vmost_set', to='bengkel.bengkel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vmost_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analisis VMOST',
                'verbose_name_plural': 'Analisis VMOST',
                'ordering': ['-created_at'],
            },
        ),
    ]
