# Generated by Django 5.0.3 on 2026-04-15 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0011_analisis5c_analisispestel_analisissoar_analisisswot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpafPainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tajuk', models.TextField(verbose_name='Tajuk / Nama Masalah')),
                ('keterangan', models.TextField(verbose_name='Huraian Masalah')),
                ('kesan', models.TextField(verbose_name='Kesan / Impak yang Dirasai')),
                ('keutamaan', models.CharField(choices=[('tinggi', 'Tinggi'), ('sederhana', 'Sederhana'), ('rendah', 'Rendah')], default='sederhana', max_length=20)),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaf_pain_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SPAF — Pain Point',
                'verbose_name_plural': 'SPAF — Pain Point',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpafProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masalah_utama', models.TextField(verbose_name='Pernyataan Masalah Utama')),
                ('skop', models.TextField(verbose_name='Skop & Batasan')),
                ('sasaran', models.TextField(verbose_name='Pihak yang Terjejas')),
                ('matlamat', models.TextField(verbose_name='Matlamat Penyelesaian')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaf_problem_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SPAF — Problem Statement',
                'verbose_name_plural': 'SPAF — Problem Statement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpafRiskAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risiko', models.TextField(verbose_name='Kenyataan Risiko')),
                ('kemungkinan', models.CharField(choices=[('tinggi', 'Tinggi'), ('sederhana', 'Sederhana'), ('rendah', 'Rendah')], default='sederhana', max_length=20)),
                ('impak', models.CharField(choices=[('tinggi', 'Tinggi'), ('sederhana', 'Sederhana'), ('rendah', 'Rendah')], default='sederhana', max_length=20)),
                ('mitigasi', models.TextField(verbose_name='Strategi Mitigasi')),
                ('pemilik', models.CharField(blank=True, max_length=200, verbose_name='Pemilik Risiko')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaf_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SPAF — Risk Analysis',
                'verbose_name_plural': 'SPAF — Risk Analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpafRootCauseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masalah', models.TextField(verbose_name='Masalah yang Dianalisis')),
                ('punca_utama', models.TextField(verbose_name='Punca Akar (Root Cause)')),
                ('punca_penyumbang', models.TextField(verbose_name='Faktor Penyumbang')),
                ('bukti', models.TextField(verbose_name='Bukti / Data Sokongan')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaf_rca', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SPAF — Root Cause Analysis',
                'verbose_name_plural': 'SPAF — Root Cause Analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpafRootCauseValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punca', models.TextField(verbose_name='Punca yang Disahkan')),
                ('kaedah', models.TextField(verbose_name='Kaedah Pengesahan')),
                ('dapatan', models.TextField(verbose_name='Dapatan Pengesahan')),
                ('kesimpulan', models.TextField(verbose_name='Kesimpulan')),
                ('catatan', models.TextField(blank=True, verbose_name='Catatan Tambahan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaf_rcv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SPAF — Root Cause Validation',
                'verbose_name_plural': 'SPAF — Root Cause Validation',
                'ordering': ['-created_at'],
            },
        ),
    ]
