# Generated by Django 5.0.3 on 2026-04-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0013_blueprinttheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
