# Generated by Django 5.0.3 on 2026-04-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0014_userprofile_alamat_userprofile_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unit',
        ),
        migrations.AddField(
            model_name='jemputan',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jemputan',
            name='unit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jemputan',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
