# Generated by Django 5.0.3 on 2026-04-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0015_remove_userprofile_alamat_remove_userprofile_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
