# Generated by Django 5.0.3 on 2026-04-21 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0016_userprofile_alamat_userprofile_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jemputan',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='jemputan',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='jemputan',
            name='username',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unit',
        ),
    ]
