# Generated by Django 5.0.3 on 2026-04-22 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bengkel', '0017_remove_jemputan_alamat_remove_jemputan_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPesan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_paparan', models.CharField(blank=True, max_length=200)),
                ('organisasi', models.CharField(blank=True, max_length=200)),
                ('mesej', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bengkel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_pesan', to='bengkel.bengkel')),
                ('pengirim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_pesan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forum Pesan',
                'verbose_name_plural': 'Forum Pesan',
                'ordering': ['-created_at'],
            },
        ),
    ]
